### ISSUE TITLE
Reorganization and cleanup of CLI Integration Tests

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#387]
CLI Integration Tests grown into a single monolithic file. I propose their reorganization and cleanup:

- Organize them into multiple "topics", make descriptions more understandable and consistent, make the code at least a little bit more DRY.
- Split them into multiple files, one "topic" per file.

### Topics

-  [x] CLI - API Description Document

-  [x] CLI - Reporters

-  [x] CLI - Server Process

-  [ ] CLI - Hooks

    ```coffee
    describe 'CLI - Hooks', ->
      describe 'When -f/--hookfiles files are provided', ->
      describe 'When -f/--hookfiles files are provided as glob', ->
      describe 'When no -f/--hookfiles file exists', ->
      describe 'When one of -f/--hookfiles files doesn\'t exist', ->
      describe 'When -f/--hookfiles files describe hooks', ->
      describe 'When -f/--hookfiles files describe events', ->
      describe 'When -f/--hookfiles files describe both hooks and events', ->
      describe 'When using -b/--sandbox to run hooks in sandbox mode', ->
    ```
-  [ ] CLI - Hooks Handler Process

    ```coffee
    describe 'CLI - Hooks Handler Process', ->
      describe 'When doesn\'t exist', ->
      describe 'When crashes before execution', ->
      describe 'When crashes during execution', ->
      describe 'When killed before execution', ->
      describe 'When killed during execution', ->
      describe 'When When didn\'t terminate and had to be killed by Dredd', ->
    ```
-  [ ] CLI - Options

    ```coffee
    describe 'CLI - Options', ->
      describe 'When -h/--header is used to add header', ->
      describe 'When -h/--header is used multiple times to add headers', ->
      describe 'When -u/--user is used to add Basic Auth credentials', ->
      describe 'When -s/--sorted is used to sort requests by method', ->
      describe 'When -e/--inline-errors is used to display errors as they occur', ->
      describe 'When -d/--details is used to display details also for passing tests', ->
      describe 'When -m/--method is used to restrict to given method', ->
      describe 'When -m/--method is used multiple times to restrict to given methods', ->
      describe 'When -x/--only is used to run only given transaction', ->
      describe 'When -x/--only is used multiple times to run only given transactions', ->
      describe 'When -c/--color is used to manage color output', ->
      describe 'When -l/--level is used to manage logger level', ->
      describe 'When -t/--timestamp is used to include timestamps', ->
      describe 'When -n/--names is used to list transaction names', ->
    ```
-  [ ] CLI - Validation

    ```coffee
    describe 'CLI - Validation', ->
      describe 'When server response matches with the API Description', ->
      describe 'When server response doesn\'t match with the API Description', ->
      describe 'When the server address contains path', ->
        describe 'When server response matches with the API Description', ->
        describe 'When server response doesn\'t match with the API Description', ->
      describe 'When API Description features schema', ->
        describe 'When server response matches with the API Description', ->
        describe 'When server response doesn\'t match with the API Description', ->
    ```

### Stage 1

First stage of this proposal has been already completed as part of https://github.com/apiaryio/dredd/pull/379, while I left the other "topics" in the original `cli-test.coffee` file.

**Comment by honzajavorek** [comment]
The file in question has been renamed from `cli-test.js` to `hookfiles-cli-test.js` in https://github.com/apiaryio/dredd/pull/1054/
