### ISSUE TITLE
Resolve all pending problems with the current Dredd hook template

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#917]
There are two main problems on the hook template, which exploded into far more complicated issues then they seemed to be:

- Aruba update
- Missing --port and --host support

Hook handler authors were trying to propose and contribute, but now it's getting complicated, stale, tangled together. I think no contributor will come and reintroduce order to things, we'll have to come and push things forward. I tried to untangle all the problems and I propose following 10 steps:

## Update Aruba

1.  Kill extraneous child processes with Aruba
    https://github.com/apiaryio/dredd-hooks-template/issues/16#issuecomment-283011220
    https://github.com/apiaryio/dredd-hooks-template/issues/6

2.  Finish update of the template in Ruby hooks
    https://github.com/apiaryio/dredd-hooks-ruby/pull/31

3.  Finish update of the template in Python hooks
    https://github.com/apiaryio/dredd-hooks-python/pull/28

4.  Update the template itself with the changes
    https://github.com/apiaryio/dredd-hooks-template/issues/16
    https://github.com/apiaryio/dredd-hooks-template/pull/15

## Add --port and --host

5.  Implement trial and error behavior in Dredd when running the hook
    handler
    https://github.com/apiaryio/dredd/pull/712#issuecomment-288979978

6.  Properly resolve hook handler arguments
    https://github.com/apiaryio/dredd/issues/742

7.  Pass --port and --host to the hook handler
    https://github.com/apiaryio/dredd/pull/712

8.  Add test for --port and --host to the template
    https://github.com/apiaryio/dredd-hooks-template/pull/17

## Propagate changes

9.  Propagate changes to all hook handlers
    https://github.com/apiaryio/dredd-hooks-template/issues/16

10. Document the process for adding things to the template
    https://github.com/apiaryio/dredd-hooks-template/issues/19

**Comment by ddelnano** [comment]
😓 really dropped the ball on coming back to #712

**Comment by honzajavorek** [comment]
Current strategy, which includes https://github.com/apiaryio/dredd-hooks-template/issues/23 as well:

- [ ] copy the template from Python hooks, so we avoid any changes (deleted files, upgraded Aruba, ...) made by Gonzalo in both the template and the Ruby hooks, pretend that Python is pseudo code
- [ ] make the tests pass for Python hooks in the CI of the template repo
- [ ] rewrite the test suite to Node.js, with Python examples kept intact, remove Ruby dependencies except for dredd_hooks https://github.com/apiaryio/dredd-hooks-template/issues/23 
- [ ] write docs on how to install / develop / upgrade the template in the hook languages (dredd docs and readme) https://github.com/apiaryio/dredd-hooks-template/issues/19 
- [ ] update of the template in Ruby hooks
- [ ] update dependencies in Ruby hooks
- [ ] update of the template in Python hooks
- [ ] update dependencies in Python hooks
- [ ] add eslint to template
- [ ] add greenkeeper to template 
- [ ] finish the rest of https://github.com/apiaryio/dredd/issues/917 (this issue)

**Comment by honzajavorek** [comment]
@ddelnano I'm about to get back to https://github.com/apiaryio/dredd/pull/712#issuecomment-288979978 and I'm wondering... would following work as well?

- Dredd runs the hooks handler only with paths to hook files if port and host are set to the default values
- If port or host are set to non-default values, then `--port`, `--host`, or both are added as options to the hooks handler command
- In case the hooks handler crashes, Dredd will terminate, but will remember that port or host change was involved and will warn user with something like "hey, perhaps the hooks handler you're using doesn't support host / port change, so don't do that..."
- In case the hooks handler doesn't crash, but Dredd isn't able to connect, it will terminate, but will remember that port or host change was involved and will warn user with something like "hey, perhaps the hooks handler you're using doesn't support host / port change, so don't do that..."
- Otherwise business as usual

What do you think?

**Comment by ddelnano** [comment]
Sorry I was in the middle of moving and then went on vacation 🍹. That sounds like the best plan for rolling out this change.

**Comment by honzajavorek** [comment]
I did most of the dirty work needed here and there's a work in progress in https://github.com/apiaryio/dredd/pull/1421 to implement the actual `--port` forwarding in Dredd.

**Comment by lukaszwit** [comment]
Hi, I would like to ask if the work is going to be continued on this issue?
